### ISSUE TITLE
The tool doesn't build anymore because of incompatibility with new version of packer

### ISSUE THREAD

**Issue by vladistan** [gosddc/packer-post-processor-vagrant-vmware-ovf#10]
Go dependency manager always pulls the HEAD of the repository for GIT imports.  Looks like @mitchellh has changed the way config templates are processed.   This causes build failure for this tool.

**Comment by frapposelli** [comment]
Thanks, I'll take a look at it.

**Comment by vladistan** [comment]
This https://github.com/vladistan/packer-post-processor-vagrant-vmware-ovf/commit/a8cf1eeb28ac48c1f6a99afcb5db9b35187c9f8b kind of fixes it except for a small problem.  It doesn't get correct name for the output image.

**Comment by mightydok** [comment]
@vladistan some errors with your patch:

Build 'vmware-iso' errored: 1 error(s) occurred:

* Post-processor failed: open debian-8.1.0-amd64_<no value>-imldev-0.0.2.box: The filename, directory name, or volume label syntax is incorrect.

==> Some builds didn't complete successfully and had errors:
--> vmware-iso: 1 error(s) occurred:

* Post-processor failed: open debian-8.1.0-amd64_<no value>-imldev-0.0.2.box: The filename, directory name, or volume label syntax is incorrect.

==> Builds finished but no artifacts were created.

**Comment by vladistan** [comment]
@mightydok Yes I know it doesn't generate correct names.... that's why I didn't create pull request yet.   Can you share your image files, so I'll see what are you trying to build?

**Comment by mightydok** [comment]
I think there is correct sample:
https://github.com/mitchellh/packer/blob/d429b75fccf5ea1332d0536172930f83ba10eafe/post-processor/vagrant/post-processor.go

2015-07-13 2:26 GMT+03:00 Vlad Korolev <notifications@github.com>:

**Comment by mightydok** [comment]
Plugin succesfully builded with this patch, can u check: https://github.com/gosddc/packer-post-processor-vagrant-vmware-ovf/commit/1488af28a48d5ecb624da02420fda07ea2683270 ?
